#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TinTuc")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertADMIN_tt(ADMIN_tt instance);
    partial void UpdateADMIN_tt(ADMIN_tt instance);
    partial void DeleteADMIN_tt(ADMIN_tt instance);
    partial void InsertCHU_DE_tt(CHU_DE_tt instance);
    partial void UpdateCHU_DE_tt(CHU_DE_tt instance);
    partial void DeleteCHU_DE_tt(CHU_DE_tt instance);
    partial void InsertTIN_TUC_tt(TIN_TUC_tt instance);
    partial void UpdateTIN_TUC_tt(TIN_TUC_tt instance);
    partial void DeleteTIN_TUC_tt(TIN_TUC_tt instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TinTucConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMIN_tt> ADMIN_tts
		{
			get
			{
				return this.GetTable<ADMIN_tt>();
			}
		}
		
		public System.Data.Linq.Table<CHU_DE_tt> CHU_DE_tts
		{
			get
			{
				return this.GetTable<CHU_DE_tt>();
			}
		}
		
		public System.Data.Linq.Table<TIN_TUC_tt> TIN_TUC_tts
		{
			get
			{
				return this.GetTable<TIN_TUC_tt>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN_tt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaAdmin;
		
		private string _TenAdmin;
		
		private string _Email;
		
		private System.Nullable<int> _SDT;
		
		private EntitySet<TIN_TUC_tt> _TIN_TUC_tts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaAdminChanging(int value);
    partial void OnMaAdminChanged();
    partial void OnTenAdminChanging(string value);
    partial void OnTenAdminChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(System.Nullable<int> value);
    partial void OnSDTChanged();
    #endregion
		
		public ADMIN_tt()
		{
			this._TIN_TUC_tts = new EntitySet<TIN_TUC_tt>(new Action<TIN_TUC_tt>(this.attach_TIN_TUC_tts), new Action<TIN_TUC_tt>(this.detach_TIN_TUC_tts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaAdmin", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaAdmin
		{
			get
			{
				return this._MaAdmin;
			}
			set
			{
				if ((this._MaAdmin != value))
				{
					this.OnMaAdminChanging(value);
					this.SendPropertyChanging();
					this._MaAdmin = value;
					this.SendPropertyChanged("MaAdmin");
					this.OnMaAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenAdmin", DbType="NChar(10)")]
		public string TenAdmin
		{
			get
			{
				return this._TenAdmin;
			}
			set
			{
				if ((this._TenAdmin != value))
				{
					this.OnTenAdminChanging(value);
					this.SendPropertyChanging();
					this._TenAdmin = value;
					this.SendPropertyChanged("TenAdmin");
					this.OnTenAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int")]
		public System.Nullable<int> SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ADMIN_TIN_TUC", Storage="_TIN_TUC_tts", ThisKey="MaAdmin", OtherKey="MaNguoiDang")]
		public EntitySet<TIN_TUC_tt> TIN_TUC_tts
		{
			get
			{
				return this._TIN_TUC_tts;
			}
			set
			{
				this._TIN_TUC_tts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TIN_TUC_tts(TIN_TUC_tt entity)
		{
			this.SendPropertyChanging();
			entity.ADMIN_tt = this;
		}
		
		private void detach_TIN_TUC_tts(TIN_TUC_tt entity)
		{
			this.SendPropertyChanging();
			entity.ADMIN_tt = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHU_DE")]
	public partial class CHU_DE_tt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChuDe;
		
		private string _TenChuDe;
		
		private EntitySet<TIN_TUC_tt> _TIN_TUC_tts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChuDeChanging(int value);
    partial void OnMaChuDeChanged();
    partial void OnTenChuDeChanging(string value);
    partial void OnTenChuDeChanged();
    #endregion
		
		public CHU_DE_tt()
		{
			this._TIN_TUC_tts = new EntitySet<TIN_TUC_tt>(new Action<TIN_TUC_tt>(this.attach_TIN_TUC_tts), new Action<TIN_TUC_tt>(this.detach_TIN_TUC_tts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuDe", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaChuDe
		{
			get
			{
				return this._MaChuDe;
			}
			set
			{
				if ((this._MaChuDe != value))
				{
					this.OnMaChuDeChanging(value);
					this.SendPropertyChanging();
					this._MaChuDe = value;
					this.SendPropertyChanged("MaChuDe");
					this.OnMaChuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChuDe", DbType="NVarChar(50)")]
		public string TenChuDe
		{
			get
			{
				return this._TenChuDe;
			}
			set
			{
				if ((this._TenChuDe != value))
				{
					this.OnTenChuDeChanging(value);
					this.SendPropertyChanging();
					this._TenChuDe = value;
					this.SendPropertyChanged("TenChuDe");
					this.OnTenChuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHU_DE_TIN_TUC", Storage="_TIN_TUC_tts", ThisKey="MaChuDe", OtherKey="MaCD")]
		public EntitySet<TIN_TUC_tt> TIN_TUC_tts
		{
			get
			{
				return this._TIN_TUC_tts;
			}
			set
			{
				this._TIN_TUC_tts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TIN_TUC_tts(TIN_TUC_tt entity)
		{
			this.SendPropertyChanging();
			entity.CHU_DE_tt = this;
		}
		
		private void detach_TIN_TUC_tts(TIN_TUC_tt entity)
		{
			this.SendPropertyChanging();
			entity.CHU_DE_tt = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TIN_TUC")]
	public partial class TIN_TUC_tt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTin;
		
		private string _TieuDe;
		
		private string _Tomtat;
		
		private string _NoiDung;
		
		private string _AnhBia;
		
		private System.Nullable<int> _MaCD;
		
		private System.Nullable<int> _MaNguoiDang;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private EntityRef<ADMIN_tt> _ADMIN_tt;
		
		private EntityRef<CHU_DE_tt> _CHU_DE_tt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTinChanging(int value);
    partial void OnMaTinChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnTomtatChanging(string value);
    partial void OnTomtatChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnAnhBiaChanging(string value);
    partial void OnAnhBiaChanged();
    partial void OnMaCDChanging(System.Nullable<int> value);
    partial void OnMaCDChanged();
    partial void OnMaNguoiDangChanging(System.Nullable<int> value);
    partial void OnMaNguoiDangChanged();
    partial void OnNgayDangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangChanged();
    #endregion
		
		public TIN_TUC_tt()
		{
			this._ADMIN_tt = default(EntityRef<ADMIN_tt>);
			this._CHU_DE_tt = default(EntityRef<CHU_DE_tt>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTin", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTin
		{
			get
			{
				return this._MaTin;
			}
			set
			{
				if ((this._MaTin != value))
				{
					this.OnMaTinChanging(value);
					this.SendPropertyChanging();
					this._MaTin = value;
					this.SendPropertyChanged("MaTin");
					this.OnMaTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tomtat", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Tomtat
		{
			get
			{
				return this._Tomtat;
			}
			set
			{
				if ((this._Tomtat != value))
				{
					this.OnTomtatChanging(value);
					this.SendPropertyChanging();
					this._Tomtat = value;
					this.SendPropertyChanged("Tomtat");
					this.OnTomtatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhBia", DbType="NChar(10)")]
		public string AnhBia
		{
			get
			{
				return this._AnhBia;
			}
			set
			{
				if ((this._AnhBia != value))
				{
					this.OnAnhBiaChanging(value);
					this.SendPropertyChanging();
					this._AnhBia = value;
					this.SendPropertyChanged("AnhBia");
					this.OnAnhBiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCD", DbType="Int")]
		public System.Nullable<int> MaCD
		{
			get
			{
				return this._MaCD;
			}
			set
			{
				if ((this._MaCD != value))
				{
					if (this._CHU_DE_tt.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCDChanging(value);
					this.SendPropertyChanging();
					this._MaCD = value;
					this.SendPropertyChanged("MaCD");
					this.OnMaCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDang", DbType="Int")]
		public System.Nullable<int> MaNguoiDang
		{
			get
			{
				return this._MaNguoiDang;
			}
			set
			{
				if ((this._MaNguoiDang != value))
				{
					if (this._ADMIN_tt.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiDangChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDang = value;
					this.SendPropertyChanged("MaNguoiDang");
					this.OnMaNguoiDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ADMIN_TIN_TUC", Storage="_ADMIN_tt", ThisKey="MaNguoiDang", OtherKey="MaAdmin", IsForeignKey=true)]
		public ADMIN_tt ADMIN_tt
		{
			get
			{
				return this._ADMIN_tt.Entity;
			}
			set
			{
				ADMIN_tt previousValue = this._ADMIN_tt.Entity;
				if (((previousValue != value) 
							|| (this._ADMIN_tt.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ADMIN_tt.Entity = null;
						previousValue.TIN_TUC_tts.Remove(this);
					}
					this._ADMIN_tt.Entity = value;
					if ((value != null))
					{
						value.TIN_TUC_tts.Add(this);
						this._MaNguoiDang = value.MaAdmin;
					}
					else
					{
						this._MaNguoiDang = default(Nullable<int>);
					}
					this.SendPropertyChanged("ADMIN_tt");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHU_DE_TIN_TUC", Storage="_CHU_DE_tt", ThisKey="MaCD", OtherKey="MaChuDe", IsForeignKey=true)]
		public CHU_DE_tt CHU_DE_tt
		{
			get
			{
				return this._CHU_DE_tt.Entity;
			}
			set
			{
				CHU_DE_tt previousValue = this._CHU_DE_tt.Entity;
				if (((previousValue != value) 
							|| (this._CHU_DE_tt.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHU_DE_tt.Entity = null;
						previousValue.TIN_TUC_tts.Remove(this);
					}
					this._CHU_DE_tt.Entity = value;
					if ((value != null))
					{
						value.TIN_TUC_tts.Add(this);
						this._MaCD = value.MaChuDe;
					}
					else
					{
						this._MaCD = default(Nullable<int>);
					}
					this.SendPropertyChanged("CHU_DE_tt");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
